// screens/add_student_screen.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:lms/controllers/student_controller.dart';
import 'package:lms/models/student.dart';
import 'package:lms/services/class_service.dart';

class AddStudentScreen extends StatefulWidget {
  @override
  _AddStudentScreenState createState() => _AddStudentScreenState();
}

class _AddStudentScreenState extends State<AddStudentScreen> {
  final _formKey = GlobalKey<FormState>();
  final _classService = ClassService();

  final _admissionNoController = TextEditingController();
  final _fullNameController = TextEditingController();
  final _fatherNameController = TextEditingController();
  final _rollNumberController = TextEditingController();
  final _addressController = TextEditingController();

  String? _selectedClassId;
  String? _selectedSectionId;
  List<dynamic> _classes = [];
  List<dynamic> _sections = [];
  DateTime? _selectedDate;

  @override
  void initState() {
    super.initState();
    _loadClasses();
  }

  Future<void> _loadClasses() async {
    try {
      final classes = await _classService.getClasses();
      setState(() {
        _classes = classes;
      });
    } catch (e) {
      print('Error loading classes: $e');
    }
  }

  Future<void> _loadSections(String classId) async {
    try {
      final sections = await _classService.getSections(classId);
      setState(() {
        _sections = sections;
        _selectedSectionId = null;
      });
    } catch (e) {
      print('Error loading sections: $e');
    }
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  Future<void> _saveStudent() async {
    if (_formKey.currentState!.validate()) {
      final student = Student(
        id: '', // Will be generated by Supabase
        admissionNo: _admissionNoController.text,
        fullName: _fullNameController.text,
        fatherName: _fatherNameController.text.isEmpty ? null : _fatherNameController.text,
        classId: _selectedClassId!,
        sectionId: _selectedSectionId,
        rollNumber: int.tryParse(_rollNumberController.text),
        academicYear: 2026,
        dateOfBirth: _selectedDate,
        address: _addressController.text.isEmpty ? null : _addressController.text,
        photoUrl: null,
        createdAt: DateTime.now(),
      );

      try {
        await Provider.of<StudentController>(context, listen: false)
            .addStudent(student);
        Navigator.pop(context);
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add student: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add Student'),
        actions: [
          IconButton(
            icon: Icon(Icons.save),
            onPressed: _saveStudent,
          ),
        ],
      ),
      body: Padding(
        padding: EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Student Details Card
              Card(
                child: Padding(
                  padding: EdgeInsets.all(24),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Student Information',
                        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                      ),
                      SizedBox(height: 24),

                      // Admission No
                      TextFormField(
                        controller: _admissionNoController,
                        decoration: InputDecoration(
                          labelText: 'Admission Number *',
                          border: OutlineInputBorder(),
                        ),
                        validator: (value) {
                          if (value == null || value.isEmpty) {
                            return 'Please enter admission number';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),

                      // Full Name
                      TextFormField(
                        controller: _fullNameController,
                        decoration: InputDecoration(
                          labelText: 'Full Name *',
                          border: OutlineInputBorder(),
                        ),
                        validator: (value) {
                          if (value == null || value.isEmpty) {
                            return 'Please enter full name';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),

                      // Father Name
                      TextFormField(
                        controller: _fatherNameController,
                        decoration: InputDecoration(
                          labelText: "Father's Name",
                          border: OutlineInputBorder(),
                        ),
                      ),
                      SizedBox(height: 16),

                      // Class and Section Row
                      Row(
                        children: [
                          Expanded(
                            child: DropdownButtonFormField<String>(
                              value: _selectedClassId,
                              decoration: InputDecoration(
                                labelText: 'Class *',
                                border: OutlineInputBorder(),
                              ),
                              items: _classes.map<DropdownMenuItem<String>>((classItem) {
                                return DropdownMenuItem<String>(
                                  value: classItem.id,
                                  child: Text(classItem.name),
                                );
                              }).toList(),
                              onChanged: (value) {
                                setState(() {
                                  _selectedClassId = value;
                                });
                                if (value != null) {
                                  _loadSections(value);
                                }
                              },
                              validator: (value) {
                                if (value == null) {
                                  return 'Please select a class';
                                }
                                return null;
                              },
                            ),
                          ),
                          SizedBox(width: 16),
                          Expanded(
                            child: DropdownButtonFormField<String>(
                              value: _selectedSectionId,
                              decoration: InputDecoration(
                                labelText: 'Section',
                                border: OutlineInputBorder(),
                              ),
                              items: _sections.map<DropdownMenuItem<String>>((section) {
                                return DropdownMenuItem<String>(
                                  value: section.id,
                                  child: Text(section.name),
                                );
                              }).toList(),
                              onChanged: (value) {
                                setState(() {
                                  _selectedSectionId = value;
                                });
                              },
                            ),
                          ),
                        ],
                      ),
                      SizedBox(height: 16),

                      // Roll Number and Date of Birth Row
                      Row(
                        children: [
                          Expanded(
                            child: TextFormField(
                              controller: _rollNumberController,
                              decoration: InputDecoration(
                                labelText: 'Roll Number',
                                border: OutlineInputBorder(),
                              ),
                              keyboardType: TextInputType.number,
                            ),
                          ),
                          SizedBox(width: 16),
                          Expanded(
                            child: InkWell(
                              onTap: () => _selectDate(context),
                              child: InputDecorator(
                                decoration: InputDecoration(
                                  labelText: 'Date of Birth',
                                  border: OutlineInputBorder(),
                                ),
                                child: Row(
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  children: [
                                    Text(
                                      _selectedDate != null
                                          ? '${_selectedDate!.day}/${_selectedDate!.month}/${_selectedDate!.year}'
                                          : 'Select Date',
                                    ),
                                    Icon(Icons.calendar_today),
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                      SizedBox(height: 16),

                      // Address
                      TextFormField(
                        controller: _addressController,
                        decoration: InputDecoration(
                          labelText: 'Address',
                          border: OutlineInputBorder(),
                        ),
                        maxLines: 3,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}